//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Shapes
{
    public class Square : Shape
    {
        public virtual double area
        {
            get;
            set;
        }

        public virtual double width
        {
            get;
            set;
        }

        public virtual double height
        {
            get;
            set;
        }

        public override double CalculateArea(object[] args)
        {
            double height = (double)args[0];
            double width = (double)args[1];

            if (width > 0 && height > 0)
                return width * height;

            return -1;
        }

        public override double CalculateCircumference(object[] args)
        {
            if (width == -1 && height > 0 && area > 0)
                return area / height;
            else if (width > 0 && height == -1 && area > 0)
                return area / width;

            return -1;
        }

    }

}